"""fix

Revision ID: 766a174d0992
Revises: 042fd823a115
Create Date: 2025-11-16 16:10:21.561678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766a174d0992'
down_revision: Union[str, None] = '042fd823a115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_chat_id'), table_name='chat')
    op.alter_column('groupchat', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('groupchat', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('groupchat', 'owner_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('groupchatmembers', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('groupchatmembers', 'group_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('groupchatmembers', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False)
    op.drop_constraint(None, 'groupchatmembers', type_='foreignkey')
    op.drop_constraint(None, 'groupchatmembers', type_='foreignkey')
    op.create_foreign_key(None, 'groupchatmembers', 'groupchat', ['group_id'], ['id'])
    op.create_foreign_key(None, 'groupchatmembers', 'user', ['user_id'], ['id'])
    op.alter_column('groupmessage', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('groupmessage', 'sender',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('groupmessage', 'group_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False)
    op.drop_index(op.f('ix_groupmessage_id'), table_name='groupmessage')
    op.drop_constraint(None, 'groupmessage', type_='foreignkey')
    op.drop_constraint(None, 'groupmessage', type_='foreignkey')
    op.create_foreign_key(None, 'groupmessage', 'user', ['sender'], ['id'])
    op.create_foreign_key(None, 'groupmessage', 'groupchat', ['group_id'], ['id'])
    op.alter_column('message', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('message', 'sender',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('message', 'user2',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['sender'], ['id'])
    op.alter_column('user', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=1)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['sender'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.alter_column('message', 'user2',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('message', 'sender',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True)
    op.alter_column('message', 'id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'groupmessage', type_='foreignkey')
    op.drop_constraint(None, 'groupmessage', type_='foreignkey')
    op.create_foreign_key(None, 'groupmessage', 'groupchat', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groupmessage', 'user', ['sender'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_groupmessage_id'), 'groupmessage', ['id'], unique=False)
    op.alter_column('groupmessage', 'group_id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True)
    op.alter_column('groupmessage', 'sender',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True)
    op.alter_column('groupmessage', 'id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'groupchatmembers', type_='foreignkey')
    op.drop_constraint(None, 'groupchatmembers', type_='foreignkey')
    op.create_foreign_key(None, 'groupchatmembers', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'groupchatmembers', 'groupchat', ['group_id'], ['id'], ondelete='CASCADE')
    op.alter_column('groupchatmembers', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True)
    op.alter_column('groupchatmembers', 'group_id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True)
    op.alter_column('groupchatmembers', 'id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('groupchat', 'owner_id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               nullable=True)
    op.alter_column('groupchat', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('groupchat', 'id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_chat_id'), 'chat', ['id'], unique=False)
    op.alter_column('chat', 'id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
